# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
      build:
          runs-on: self-hosted
          steps:
          - uses: actions/checkout@v2
          - name: cmake
              run: mkdir build; cd build; cmake ..
          - name: make
              run: cd build/; make
          - name: run
              run: cd build/; ctest
