name: ci

on: [push, pull_request]

jobs:
  build:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: mkdir build; cd build; cmake ..
    - name: make
      run: cd build/; make
    - name: run
      run: cd build/; ctest
